<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.4.6" />
    <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AuthService\Auth.API\Auth.API.csproj" />
    <ProjectReference Include="..\..\Teach.Gateway\Teach.Gateway.csproj" />
    <ProjectReference Include="..\..\TeachService\Teach.API\Teach.API.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>b6b773bb-d7d8-4a6a-af56-67a22ae83da7</UserSecretsId>
  </PropertyGroup>

</Project>
